######################################################################
##
## Filename: tb_wave.fdo
## Created on: Mon Nov 25 21:39:30 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation windows.
##
######################################################################

add wave \
-label clk sim:/tb/uut/ACLK \
-label resetn sim:/tb/uut/ARESETN \
-label s_data -hex sim:/tb/uut/S_AXIS_TDATA \
-label s_keep -hex sim:/tb/uut/S_AXIS_TKEEP \
-label s_valid -hex sim:/tb/uut/S_AXIS_TVALID \
-label s_ready sim:/tb/uut/S_AXIS_TREADY \
-label s_last sim:/tb/uut/S_AXIS_TLAST \
-label m_data -hex sim:/tb/uut/M_AXIS_TDATA \
-label m_keep sim:/tb/uut/M_AXIS_TKEEP \
-label m_valid -hex sim:/tb/uut/M_AXIS_TVALID \
-label m_ready sim:/tb/uut/M_AXIS_TREADY \
-label m_last sim:/tb/uut/M_AXIS_TLAST
